professions = [
    "Ingénieur(e) logiciel",
    "Médecin",
    "Avocat(e)",
    "Enseignant(e)",
    "Infirmier(e)",
    "Comptable",
    "Architecte",
    "Pharmacien(ne)",
    "Ingénieur(e) en mécanique",
    "Ingénieur(e) électricien",
    "Ingénieur(e) civil",
    "Économiste",
    "Psychologue",
    "Vétérinaire",
    "Chimiste",
    "Biologiste",
    "Physicien(ne)",
    "Mathématicien(ne)",
    "Statisticien(ne)",
    "Designer graphique",
    "Rédacteur(e) technique",
    "Traducteur(e)",
    "Chef cuisinier(ière)",
    "Boulanger(ère)",
    "Pâtissier(ière)",
    "Barman(Barmaid)",
    "Serveur(euse)",
    "Hôte(sse) de l'air",
    "Steward",
    "Pilote",
    "Contrôleur(e) aérien",
    "Agent(e) de bord",
    "Mécanicien(ne) automobile",
    "Électricien(ne)",
    "Plombier(ière)",
    "Charpentier(ière)",
    "Peintre en bâtiment",
    "Maçon",
    "Paysagiste",
    "Coiffeur(euse)",
    "Esthéticien(ne)",
    "Journaliste",
    "Éditeur(e)",
    "Photographe",
    "Vidéaste",
    "Animateur(e) radio",
    "Producteur(trice) de musique",
    "Artiste"
]


def get_liste_metier():
    return professions
